apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-app
  labels:
    project: microservice
    app: github-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: github-app
  template:
    metadata:
      labels:
        app: github-app
    spec:
      containers:
        - name: github-app
          image: err/github-app
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080
              name: ghapp-port
          env:
            - name: GITHUB_WEB_URL
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: GITHUB_WEB_URL
            - name: GITHUB_V3_API_URL
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: GITHUB_V3_API_URL
            - name: GITHUB_V4_API_URL
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: GITHUB_V4_API_URL
            - name: RPC_URL
              valueFrom:
                secretKeyRef:
                  name: secret-vault
                  key: RPC_URL
            - name: NETWORK_NAME
              valueFrom:
                secretKeyRef:
                  name: secret-vault
                  key: NETWORK_NAME
            - name: GITHUB_APP_INTEGRATION_ID
              valueFrom:
                secretKeyRef:
                  name: secret-vault
                  key: GITHUB_APP_INTEGRATION_ID
            - name: GITHUB_APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-vault
                  key: GITHUB_APP_PRIVATE_KEY
            - name: GITHUB_APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secret-vault
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_APP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-vault
                  key: GITHUB_OAUTH_CLIENT_SECRET
            - name: GITHUB_APP_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-vault
                  key: GITHUB_APP_WEBHOOK_SECRET
            - name: GITHUB_APP_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-vault
                  key: GITHUB_APP_WEBHOOK_SECRET
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-vault
                  key: KAFKA_PASSWORD

---
## Service
apiVersion: v1
kind: Service
metadata:
  name: github-app-srv
  labels:
    project: microservice
    app: github-app-srv
spec:
  ports:
    - name: ghapp-port-ext
      port: 80
      protocol: TCP
      targetPort: ghapp-port
  selector:
    app: github-app

---
## Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: ghapp-lb
  labels:
    project: microservice
    app: ghapp-lb
spec:
  type: LoadBalancer
  selector:
    app: github-app
  ports:
    - name: "80"
      port: 8080
      targetPort: ghapp-port
      protocol: TCP
