
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: kafka-storage
  resources:
    requests:
      storage: 1Gi  

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName:  kafka-storage
  hostPath:
    path: /tmp/var/lib/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
       - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - docker-desktop 




