[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
identity = "3rQketG7pSopHE1APQKZu1BQofanqbCBP7spZ4CBGrUm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kristoffer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
