# sh into the solana container
solana_sh:
	docker run -it err/solana sh

# Build the identity sdk 
build_sdk:
    @echo "Building identity SDK..."
    anchor run build_sdk

# Build the identity program
build_program:
    @echo "Building identity..."
    anchor build 

# Build identity project
build: build_program build_sdk

# Test project using the sdk
test: build_sdk
    @echo "Testing identity SDK..."
    anchor test

# Deploy project to devnet
deploy_devnet:
    @echo "Deploying Identity to devnet ..."
    anchor deploy --provider.cluster devnet --provider.wallet ~/.config/solana/id.json

deploy_local:
    @echo "Deploying Identity to localnet ..."
    anchor deploy --provider.cluster localnet --provider.wallet ~/.config/solana/id.json


# Deploy identity to a specific RPC_URL
deploy RPC_URL:
    @echo "Deploying identity to RPC..."
    anchor deploy --provider.cluster {{RPC_URL}} --provider.wallet ~/.config/solana/id.json

# Recover fees in case deployment failed
recover_deploy:
    @echo "Recovering identity..."
    solana-keygen recover -o recover.json
    solana program close recover.json

# Grind for keypair starting with PREFIX
grind_key PREFIX:
    @echo "Grinding for keypair starting with $(PREFIX)..."
    solana-keygen grind --starts-with {{PREFIX}}:1 --ignore-case

# Generate local keypair
generate_keypair NAME:
    @echo "Generating keypair..."
    solana-keygen new -o ~/.config/solana/{{NAME}}.json --no-bip39-passphrase

# Get program keypair address
program_address:
    @echo "Checking program address..."
    solana address --keypair target/deploy/identity-keypair.json

airdrop: 
    @echo "Airdropping..."
    solana airdrop -u devnet -k ~/.config/solana/id.json 1


balance: 
    @echo "Checking balance..."
    solana balance

# Release SDK
release_sdk:
    @echo "Releasing identity..."
    yarn run release:sdk