// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: proto/index.proto

package bounty

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BountySignStatus int32

const (
	BountySignStatus_CREATED        BountySignStatus = 0
	BountySignStatus_SIGNED         BountySignStatus = 1
	BountySignStatus_COMPLETED      BountySignStatus = 2
	BountySignStatus_FAILED_TO_SIGN BountySignStatus = 3
	BountySignStatus_CANCELLED      BountySignStatus = 4
)

// Enum value maps for BountySignStatus.
var (
	BountySignStatus_name = map[int32]string{
		0: "CREATED",
		1: "SIGNED",
		2: "COMPLETED",
		3: "FAILED_TO_SIGN",
		4: "CANCELLED",
	}
	BountySignStatus_value = map[string]int32{
		"CREATED":        0,
		"SIGNED":         1,
		"COMPLETED":      2,
		"FAILED_TO_SIGN": 3,
		"CANCELLED":      4,
	}
)

func (x BountySignStatus) Enum() *BountySignStatus {
	p := new(BountySignStatus)
	*p = x
	return p
}

func (x BountySignStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BountySignStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_index_proto_enumTypes[0].Descriptor()
}

func (BountySignStatus) Type() protoreflect.EnumType {
	return &file_proto_index_proto_enumTypes[0]
}

func (x BountySignStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BountySignStatus.Descriptor instead.
func (BountySignStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_index_proto_rawDescGZIP(), []int{0}
}

type BountyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BountySignStatus BountySignStatus `protobuf:"varint,1,opt,name=BountySignStatus,proto3,enum=bounty.BountySignStatus" json:"BountySignStatus,omitempty"`
	Bountyid         int64            `protobuf:"varint,2,opt,name=Bountyid,proto3" json:"Bountyid,omitempty"`
	BountyUIAmount   string           `protobuf:"bytes,3,opt,name=BountyUIAmount,proto3" json:"BountyUIAmount,omitempty"`
	TokenAddress     string           `protobuf:"bytes,4,opt,name=TokenAddress,proto3" json:"TokenAddress,omitempty"`
	CreatorAddress   string           `protobuf:"bytes,5,opt,name=CreatorAddress,proto3" json:"CreatorAddress,omitempty"`
	InstallationId   int64            `protobuf:"varint,6,opt,name=InstallationId,proto3" json:"InstallationId,omitempty"`
	Platform         string           `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`
	Organization     string           `protobuf:"bytes,8,opt,name=organization,proto3" json:"organization,omitempty"`
	Team             string           `protobuf:"bytes,9,opt,name=team,proto3" json:"team,omitempty"`
	DomainType       string           `protobuf:"bytes,10,opt,name=domainType,proto3" json:"domainType,omitempty"`
}

func (x *BountyMessage) Reset() {
	*x = BountyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_index_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BountyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BountyMessage) ProtoMessage() {}

func (x *BountyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_index_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BountyMessage.ProtoReflect.Descriptor instead.
func (*BountyMessage) Descriptor() ([]byte, []int) {
	return file_proto_index_proto_rawDescGZIP(), []int{0}
}

func (x *BountyMessage) GetBountySignStatus() BountySignStatus {
	if x != nil {
		return x.BountySignStatus
	}
	return BountySignStatus_CREATED
}

func (x *BountyMessage) GetBountyid() int64 {
	if x != nil {
		return x.Bountyid
	}
	return 0
}

func (x *BountyMessage) GetBountyUIAmount() string {
	if x != nil {
		return x.BountyUIAmount
	}
	return ""
}

func (x *BountyMessage) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *BountyMessage) GetCreatorAddress() string {
	if x != nil {
		return x.CreatorAddress
	}
	return ""
}

func (x *BountyMessage) GetInstallationId() int64 {
	if x != nil {
		return x.InstallationId
	}
	return 0
}

func (x *BountyMessage) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *BountyMessage) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *BountyMessage) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *BountyMessage) GetDomainType() string {
	if x != nil {
		return x.DomainType
	}
	return ""
}

type LinkerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username      string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	UserId        string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	WalletAddress string `protobuf:"bytes,3,opt,name=WalletAddress,proto3" json:"WalletAddress,omitempty"`
}

func (x *LinkerMessage) Reset() {
	*x = LinkerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_index_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkerMessage) ProtoMessage() {}

func (x *LinkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_index_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkerMessage.ProtoReflect.Descriptor instead.
func (*LinkerMessage) Descriptor() ([]byte, []int) {
	return file_proto_index_proto_rawDescGZIP(), []int{1}
}

func (x *LinkerMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LinkerMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LinkerMessage) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

var File_proto_index_proto protoreflect.FileDescriptor

var file_proto_index_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x22, 0x81, 0x03, 0x0a, 0x0d,
	0x42, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x44, 0x0a,
	0x10, 0x42, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x62, 0x6f, 0x75, 0x6e, 0x74, 0x79,
	0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x10, 0x42, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x69, 0x64, 0x12,
	0x26, 0x0a, 0x0e, 0x42, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x55, 0x49, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x42, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x55,
	0x49, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x61, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x12,
	0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x69, 0x0a, 0x0d, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2a, 0x5d, 0x0a, 0x10, 0x42, 0x6f,
	0x75, 0x6e, 0x74, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b,
	0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x49, 0x47, 0x4e, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c,
	0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44,
	0x5f, 0x54, 0x4f, 0x5f, 0x53, 0x49, 0x47, 0x4e, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41,
	0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2f, 0x62, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_index_proto_rawDescOnce sync.Once
	file_proto_index_proto_rawDescData = file_proto_index_proto_rawDesc
)

func file_proto_index_proto_rawDescGZIP() []byte {
	file_proto_index_proto_rawDescOnce.Do(func() {
		file_proto_index_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_index_proto_rawDescData)
	})
	return file_proto_index_proto_rawDescData
}

var file_proto_index_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_index_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_index_proto_goTypes = []interface{}{
	(BountySignStatus)(0), // 0: bounty.BountySignStatus
	(*BountyMessage)(nil), // 1: bounty.BountyMessage
	(*LinkerMessage)(nil), // 2: bounty.LinkerMessage
}
var file_proto_index_proto_depIdxs = []int32{
	0, // 0: bounty.BountyMessage.BountySignStatus:type_name -> bounty.BountySignStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_index_proto_init() }
func file_proto_index_proto_init() {
	if File_proto_index_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_index_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BountyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_index_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_index_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_index_proto_goTypes,
		DependencyIndexes: file_proto_index_proto_depIdxs,
		EnumInfos:         file_proto_index_proto_enumTypes,
		MessageInfos:      file_proto_index_proto_msgTypes,
	}.Build()
	File_proto_index_proto = out.File
	file_proto_index_proto_rawDesc = nil
	file_proto_index_proto_goTypes = nil
	file_proto_index_proto_depIdxs = nil
}
